services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: flights_app
    environment:
      - TZ=Europe/Brussels
    env_file: .env
    depends_on:
      - redis_cache
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    command: python app/main.py   # <--- ensure this matches

  redis_cache:
    image: redis:7
    container_name: redis_cache
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
